CREATE TABLE tb_sedes(
	id SERIAL PRIMARY KEY NOT NULL,
	pais VARCHAR(100) NOT NULL,
	estado VARCHAR(100) NOT NULL,
	cidade VARCHAR(100) NOT NULL,
	logradouro VARCHAR(255) NOT NULL,
	numero NUMERIC(20) NOT NULL,
	cep NUMERIC(20) NOT NULL,
	complemento VARCHAR(255) NOT NULL
)